# Use an official Airflow image as the base
FROM apache/airflow:2.6.1

# Set environment variables for Airflow
ENV AIRFLOW_HOME=/opt/airflow
ENV AIRFLOW__CORE__LOAD_EXAMPLES=False
ENV AIRFLOW__CORE__EXECUTOR=SequentialExecutor

RUN python -m pip install --upgrade pip
RUN pip install pandas
RUN pip install psycopg2-binary

# Copy DAGs into the Airflow DAGs folder
COPY ./dags /opt/airflow/dags

# Initialize the Airflow DB
RUN airflow db init
RUN airflow users  create --role Admin --username admin --email admin --firstname admin --lastname admin --password admin

# Expose ports (8080 for the webserver)
EXPOSE 8080

# Command to start Airflow webserver and scheduler
CMD ["airflow", "webserver", "--port", "8080"] & \
    ["airflow", "scheduler"]